### ISSUE TITLE
Landsat project nowarp CImgInstanceException

### ISSUE THREAD

**Issue by mcorbiere** [matthewhanson/gips#15]
The below are two examples of command line prompts that produced this exception. I think it has something to do with the nowarp switch. This happened a bunch of other times, but I'm not sure of all the instances/products. However, the images produced from this command line seem to be fine (they show up in the right spot in qgis at least).

mcorbier@nile:/titan/projects/cyanomap/data/fieldwork2014/lakes_visited$ landsat project -s greatbay.shp -d 2014-269 -p volref --nowarp GIPS Landsat utility v0.8.0b3 Processing 1 files: volref -> 012030_2014269_LC8_volref.tif: processed in 0:00:55.827178 Completed processing in 0:01:25.108703 Creating GIPS project greatbay_30.0_Landsat Dates: 1 dates (2014-09-26 - 2014-09-26) Products: volref

[CImg] CImgInstanceException [instance(0,0,0,0,(nil),non-shared)] CImg<double>::CImg(): Failed to allocate memory (15846.1 Gio) for image (823,2584239115,1,1). Completed GIPS project in 0:00:02.191977 DATE Products 2014 213 ref 245 ref 261 acca fmask rad-toa rad-toa-masked ref ref-masked ref-toa ref-toa-masked volref volref-masked wtemp wtemp-masked 269 ref ref-toa volref
17 files on 4 dates
SENSORS LC8 LE7 

mcorbier@nile:/titan/projects/cyanomap/data/fieldwork2014/lakes_visited$
I just got that same CImgInstanceException for another image/products if that helps...
mcorbier@nile:/titan/projects/cyanomap/data/fieldwork2014/lakes_visited$ landsat project -s bowlake.shp -d 2014-237 -p dn --nowarp GIPS Landsat utility v0.8.0b3 Processing 1 files: dn -> 012030_2014237_LC8_dn.tif: processed in 0:00:49.841905 Completed processing in 0:01:12.961996 Creating GIPS project bowlake_30.0_Landsat Dates: 1 dates (2014-08-25 - 2014-08-25) Products: dn

[CImg] CImgInstanceException [instance(0,0,0,0,(nil),non-shared)] CImg<double>::CImg(): Failed to allocate memory (3533.7 Gio) for image (128,3705355281,1,1). Completed GIPS project in 0:00:00.969787 DATE Products 2014 237 dn
1 files on 1 dates
SENSORS LC8 

mcorbier@nile:/titan/projects/cyanomap/data/fieldwork2014/lakes_visited$

**Comment by ircwaves** [comment]
@mcorbiere -- can you verify that this bug still exists?

**Comment by mcorbiere** [comment]
Tested projecting the first example (greatbay.shp) on rio (v0.8.1) with no exception. The --nowarp switch is no longer.
