### ISSUE TITLE
gips_project stack products

### ISSUE THREAD

**Issue by mcorbiere** [matthewhanson/gips#18]
mcorbier@nile:/titan/projects/cyanomap/data/lake_temperature/champlain$ gips_project stack champlain_30.0_Landsat/test/ -p wtemp-masked
GIPS (v0.8.0b4): GIPS Project Utilities (v1.0.0)
Error in GIPS Project Utilities: 'wtemp-masked'

It seems we can't stack masked products? Or maybe it's just a problem with wtemp.

mcorbier@nile:/titan/projects/cyanomap/data/lake_temperature/champlain$ gips_project stack champlain_30.0_Landsat/test/ -p wtemp
GIPS (v0.8.0b4): GIPS Project Utilities (v1.0.0)
Error in GIPS Project Utilities: 'wtemp'

mcorbier@nile:/titan/projects/cyanomap/data/lake_temperature/champlain$ gips_project stack champlain_30.0_Landsat/test/
GIPS (v0.8.0b4): GIPS Project Utilities (v1.0.0)
Error in GIPS Project Utilities: 'wtemp'

**Comment by ircwaves** [comment]
I have never heard of `gips_project stack`.  Is this still needed/used?

**Comment by mcorbiere** [comment]
I only vaguely remember this. I was trying to stack a timeseries of landsat images to do a pixel level analysis. I ended up using gdal to create my stacked image, though gdal will only give band names to the first 55 bands in an image. I suppose if gippy were to do this, it would have that limitation as well since it uses gdal. I assume Matt mentioned that gips_project stack could have been an option, otherwise I'm not sure how I would have heard of it. I don't see it as an option now, but maybe it could be an add on if people would find it useful.

**Comment by ircwaves** [comment]
This pertains to an old version of `gips_project`.  If we need stacking functionality in the future this issue does note the 55 band-name limitation.
