### ISSUE TITLE
gips project file names

### ISSUE THREAD

**Issue by bhbraswell** [matthewhanson/gips#19]
gips_project creates file names that override the naming convention set in gips project.

what is the proper behavior? can the "sensor" name be set as a configuration parameter?

for example: MODIS obstime products are like
h11v08_2004325_MOD-MYD_obstime.tif

but the project files are like
2004325_MCD_obstime.tif

In this case they should be "MOD-MYD", since only the BRDF-adjusted products are MCD.
I think the convention is that MCD is for when the algorithm uses both terra and aqua data.

**Comment by bhbraswell** [comment]
Update: it appears to override the product sensor name only sometimes, randomly?

**Comment by matthewhanson** [comment]
The sensor name should be the same in the project output as it is on the back-end tiles.   MOD-MYD means that the product contains bands from both MOD and MYD, while MCD means that a single band is derived from both.

Is there a simple case which illustrates this behavior?

**Comment by ircwaves** [comment]
marked won't fix based on Rob no longer having problems with this.  There could be issues with sensor in the naming convention in the future.
