### ISSUE TITLE
db connection for tile vectors

### ISSUE THREAD

**Issue by matthewhanson** [matthewhanson/gips#20]
Changing the tile vector (the tile that describes the sensor tiling system) to use a database fails to connect to the vector in the DB.

**Comment by matthewhanson** [comment]
Changed issue from db connection problem to more general issue of user defined tiles vectors.   Could be in database or anywhere else.

**Comment by matthewhanson** [comment]
Keeping this issue as just db connection problem, #22 is feature request.   This would probably be fixed while doing #22

**Comment by ircwaves** [comment]
As `tile.shp` vector is now part of the data driver, this now seems fixed/invalid.
