### ISSUE TITLE
Is scipy a dependendency?

### ISSUE THREAD

**Issue by bhbraswell** [matthewhanson/gips#23]
Scipy is listed but I don't see it imported anywhere.

**Comment by matthewhanson** [comment]
It might not be anymore.  It was used in the temporal classifier, but now that is part of it's own repository (gips-bin) with a couple other scripts.

**Comment by matthewhanson** [comment]
scipy and matplotlib are required for Py6S, and for some reason don't show up in the Py6S setup file, which is where they belong.   I issued a PR to Py6S with those changes so they can be removed from here
