### ISSUE TITLE
output extent incorrect

### ISSUE THREAD

**Issue by matthewhanson** [matthewhanson/gips#25]
It  appears that with the current verion gips_project is not generating output files with the correct extent.

New files are ~5% smaller in each dimension on a test case, and the corner points are inside of the shapefile rather than lining up.  More investigation needed as to what the problem.

**Comment by dchowdhury** [comment]
dchowdhury@nile:/titan/work/dchowdhury/RICE_DSS/SacramentoValley/tile_044033/site_30.0_CDL$gips_project CDL -s ../site.shp -t CA -d 2014 -p cdl --res 30.0 30.0

Resultant file has size 7444, 7103 where as previously same shapefile created images of size 7614, 7563 (for -d 2007,2013). Might be handy to note that when I say 'previously' I mean using the older gips version. Back then I used the --nowarp option for project.

File sizes need to be identical so as to be further used by gips_tclass.

Thanks.

**Comment by matthewhanson** [comment]
I was trying to figure out what the problem is here.

gips_project appears to be working fine, and as intended.   The older files actually have some extra padding of nodata values - it did not create a raster with the exact same extent, it went out slightly larger to the west and south.   

However, you said these files were created using the older GIPS version with the --nowarp option.  But with nowarp these files should be in the original projection of the CDL (NAD83), but they aren't.  They are all UTM 10N, as the shapefile site.shp is.

So I'm not exactly sure why the old ones have the extra padding, but I'm also not sure how they were created. It looks like they were created using project as normal.    If this is the case then it the way the extent was created must have been changed.    I'm afraid that the only way to really fix this is to rerun gips_project for the CDL and Landsat data.
