### ISSUE TITLE
masking via GeoImage.Process() doesn't update image

### ISSUE THREAD

**Issue by ircwaves** [matthewhanson/gips#27]
As described above, no-arg form of `Process`  doesn't update the image.  Curiously, if you read the array (`GeoImage.Read()`) or if you write to another file (`GeoImage.Process(otro_archivo)`) the masks are appropriately applied.

**Comment by matthewhanson** [comment]
Is this due to the image not being opened in write mode?  It used to be write was the default but now you have to pass it true a the second argument to the GeoImage constructor.

**Comment by matthewhanson** [comment]
It should throw an error if read only.

**Comment by matthewhanson** [comment]
As in, it currently doesn't throw an error but it should, not "it should have if opened read only and Process is called"

**Comment by ircwaves** [comment]
That sounds likely.  I didn't know that the default behaviour had changed.  I'll see if it works with `update=True`

**Comment by ircwaves** [comment]
adding the `True` took care of it.
