### ISSUE TITLE
Use spatial query to identify tiles based on project domain(s)

### ISSUE THREAD

**Issue by bhbraswell** [matthewhanson/gips#30]
The number of features in a project domain (e.g. "-s shapefile") and in the data tile definition can both be large. Thus using -s can result in a long wait for GIPS to identify the tiles that are needed to process. A spatial based query could decrease the wait time.

**Comment by matthewhanson** [comment]
I think this can be done using SQL directly in OGR API calls and letting OGR decide what to do - this would be better as it work regardless of the format of the tiles (shapefile or db).

Not sure how long this would take.   Just doing the query is one thing, but then calculating resulting overlaps might be something else.

**Comment by ircwaves** [comment]
I believe you fixed this.
