### ISSUE TITLE
gips_mosaic error

### ISSUE THREAD

**Issue by bhbraswell** [matthewhanson/gips#34]
rbraswell@nile:~$ gips_mosaic Landsat --help
Traceback (most recent call last):
  File "/usr/local/bin/gips_mosaic", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2749, in <module>
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 446, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 459, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 628, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: gips==0.8.0b6

**Comment by matthewhanson** [comment]
Looks like something is up with the install on nile maybe. Not sure.

**Comment by ircwaves** [comment]
Assuming that it is old-installation cruft.  The scripts that should be there would be the ones in the `gips/scripts` directory of the repo, correct? (prefixed with `gips_` on each script, of course)

**Comment by mcorbiere** [comment]
After talking with Ian, it appears that gips_mosaic no longer exists. The utilities that exist are in the gips/scripts directory of the repo. This includes inventory, process, project, archive, info, mask, stats, tiles, and **init**. Then we have our AGS ones on BitBucket that include tclass, regression, and fda. 

So, looks like we just need to clean up what comes up on nile when you type gips.

**Comment by matthewhanson** [comment]
Init should not be in there....should have skipped **init** it when installing.

**Comment by matthewhanson** [comment]
Originally, gips was installed to nile via pip, to keep to regular version releases.

However, due to a problem with the way the cfg file is read from the production version caused an issue when trying to use a development version in a virtual environment.    See issue #22
