### ISSUE TITLE
gips.inventory.DataInventory.mosaic returns None

### ISSUE THREAD

**Issue by ircwaves** [matthewhanson/gips#36]
At a point recently, gips had `DataInventory.project`.  `.project` had returned a `ProjectInventory` from a `DataInventory`.  This then became `.mosaic` and functioned the same ( 99bd541cf8544b2e1b31b382d008a8326c2df4b8 ).   Now with the addition of the `tree` parameter, it returns `None`.

Can the original behavior be restored in a way that doesn't break the `tree` framework?

**Comment by matthewhanson** [comment]
What it should probably do is return a list of ProjectInventory objects....would that work?

**Comment by ircwaves** [comment]
Not sure.  I am going to just try `mosiac` and then create a
`ProjectInventory` from the directory.  That might mimic the old
functionality.

**Comment by matthewhanson** [comment]
yes, that should work.   But you are right, it should return the result, I think as a list.
