### ISSUE TITLE
Product inter-dependencies

### ISSUE THREAD

**Issue by bhbraswell** [matthewhanson/gips#38]
I think there currently isn't a standard way to indicate that a product to be generated by gips_process depends on an existing product. I'm adding a "products" field to the _products attribute in the custom Data class, right underneath the assets field. e.g. 

```
    'l2chlfill': {
        'description': 'Chlorophyll A Concentration',
        'assets': ['terra', 'aqua'],
        'products': ['l2chlraw'],
        'sensor': 'C'
```

I'm not sure if there's a better way to do this.

**Comment by ircwaves** [comment]
Will be looking at fixing this in the AGS fork....if it gets well sorted, maybe it can make it back here.
